// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/cutecarti/db-ops/internal/config"
	"github.com/cutecarti/db-ops/internal/delivery/http"
	"github.com/cutecarti/db-ops/internal/delivery/http/handlers"
	"github.com/cutecarti/db-ops/internal/repository"
	"github.com/cutecarti/db-ops/internal/repository/db"
	"github.com/cutecarti/db-ops/internal/server"
	"github.com/cutecarti/db-ops/internal/service"
	"github.com/jackc/pgx/v5/pgxpool"
	"net/http"
)

// Injectors from wire.go:

func InitServer(ctx context.Context) (*server.Server, func(), error) {
	settings, err := config.GetCfg(ctx)
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup, err := providePool(ctx, settings)
	if err != nil {
		return nil, nil, err
	}
	recordRepo := repository.NewRecordRepo(pool)
	dbService := service.NewDBService(recordRepo)
	recordHandler := handlers.NewRecordHandler(dbService)
	handler := router.NewRouter(recordHandler)
	serverServer := provideServer(handler)
	return serverServer, func() {
		cleanup()
	}, nil
}

// wire.go:

func providePool(ctx context.Context, cfg *config.Settings) (*pgxpool.Pool, func(), error) {
	pool, err := db.MakeNewPool(ctx, cfg.DB_URL)
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		pool.Close()
	}

	return pool, cleanup, nil
}

func provideServer(r http.Handler) *server.Server {
	return server.NewServer(":8000", r)
}
